/**
 * ABI drift gate (enhancement E5): every event/error fragment hand-declared in
 * src/abis.ts must exist, byte-for-byte (modulo internalType), in the compiler-
 * generated ABI JSONs under abis/. If this test fails, the contracts changed and
 * src/abis.ts (and the committed abis/*.json, regenerated by CI) must be updated.
 */
import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { ACTION_LOGGER_ABI, SIGILKIT_ERRORS_ABI } from "../src/abis.js";

const HERE = dirname(fileURLToPath(import.meta.url));

/**
 * Single source of truth for the ABI drift gate: the CI regeneration loop in
 * .github/workflows/ci.yml reads this same file, so a contract cannot be listed on one
 * side of the gate and omitted on the other.
 *
 * Regression this pins (BUG-2): SigilKitDelegator.json was committed and consumed here,
 * but was absent from the CI loop — so its ABI could go stale and still pass CI.
 */
function findRepoRoot(from: string): string {
  let dir = from;
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(dir, "scripts", "abi-targets.txt"))) return dir;
    dir = dirname(dir);
  }
  throw new Error("could not locate scripts/abi-targets.txt from " + from);
}

const ABIS_DIR = join(HERE, "..", "abis");

const GENERATOR_ABI_NAMES = readFileSync(
  join(findRepoRoot(HERE), "scripts", "abi-targets.txt"),
  "utf8",
)
  .split("\n")
  .map((l) => l.replace(/#.*$/, "").trim())
  .filter((l) => l.length > 0);

// Every listed contract must actually have a committed ABI — otherwise the gate is
// silently vacuous for that contract.
const MISSING_ABI_FILES = GENERATOR_ABI_NAMES.filter(
  (name) => !existsSync(join(ABIS_DIR, `${name}.json`)),
);

type AbiItem = {
  type: string;
  name?: string;
  inputs?: Array<{ name: string; type: string; indexed?: boolean }>;
};

function loadGenerated(): AbiItem[] {
  const items: AbiItem[] = [];
  for (const name of GENERATOR_ABI_NAMES) {
    const raw = JSON.parse(readFileSync(join(HERE, "..", "abis", `${name}.json`), "utf8")) as AbiItem[];
    items.push(...raw);
  }
  return items;
}

function signatureOf(item: AbiItem): string {
  const types = (item.inputs ?? []).map((i) => i.type).join(",");
  return `${item.name}(${types})`;
}

describe("ABI drift gate (E5)", () => {
  const generated = loadGenerated();

  it("abis/*.json exist and contain every hand-declared event/error fragment", () => {
    expect(generated.length).toBeGreaterThan(10);
    const generatedSigs = new Map(generated.map((i) => [signatureOf(i), i]));
    for (const fragment of [...ACTION_LOGGER_ABI, ...SIGILKIT_ERRORS_ABI]) {
      const item = fragment as unknown as AbiItem;
      const match = generatedSigs.get(signatureOf(item));
      expect(match, `${signatureOf(item)} missing from generated ABIs`).toBeDefined();
      // Indexed flags must match for events (decodeEventLog depends on them).
      const declaredInputs = item.inputs ?? [];
      const generatedInputs = match!.inputs ?? [];
      for (let i = 0; i < declaredInputs.length; i++) {
        expect(generatedInputs[i]?.indexed, `${signatureOf(item)} input ${i} indexed flag`).toBe(
          declaredInputs[i]!.indexed,
        );
      }
    }
  });

  it("generated ABIs declare no ERROR that abis.ts lacks (surfaces new items)", () => {
    // Errors must be complete — decodeSigilKitError's registry covers the full custom
    // error surface. Events are decoded per-need (ActionLogger events live in
    // ACTION_LOGGER_ABI); admin lifecycle events are intentionally not mirrored.
    const declared = new Set(
      [...ACTION_LOGGER_ABI, ...SIGILKIT_ERRORS_ABI].map((i) => signatureOf(i as unknown as AbiItem)),
    );
    const generatedErrors = generated
      .filter((i) => i.type === "error")
      .map((i) => signatureOf(i));
    const missing = generatedErrors.filter((sig) => !declared.has(sig));
    expect(
      missing,
      "new contract errors must be added to src/abis.ts (and decoded where relevant)",
    ).toEqual([]);
  });

  it("every contract in scripts/abi-targets.txt has a committed ABI file", () => {
    expect(
      MISSING_ABI_FILES,
      "add the missing abis/<name>.json or remove the contract from scripts/abi-targets.txt",
    ).toEqual([]);
  });

  it("the ABI target list covers the EIP-7702 delegator (BUG-2 regression pin)", () => {
    // SigilKitDelegator.json was committed and consumed by this gate, but was absent
    // from the CI regeneration loop — so a change to SigilKitDelegator.sol could land
    // with a stale committed ABI and still pass CI. Pin it into the shared list.
    expect(GENERATOR_ABI_NAMES).toContain("SigilKitDelegator");
    expect(GENERATOR_ABI_NAMES.length).toBeGreaterThanOrEqual(4);
  });

  it("CI regenerates ABIs from the same shared list (both sides of the gate agree)", () => {
    // The gate is only meaningful if CI and this test read the SAME source of truth.
    const ci = readFileSync(
      join(findRepoRoot(HERE), ".github", "workflows", "ci.yml"),
      "utf8",
    );
    expect(
      ci,
      "ci.yml must regenerate ABIs from scripts/abi-targets.txt, not a hand-written list",
    ).toContain("scripts/abi-targets.txt");
    // Guard against a re-introduced hardcoded loop.
    expect(ci).not.toMatch(/for c in SessionKeyManager/);
  });
});
