/**
 * ABI drift gate (enhancement E5): every event/error fragment hand-declared in
 * src/abis.ts must exist, byte-for-byte (modulo internalType), in the compiler-
 * generated ABI JSONs under abis/. If this test fails, the contracts changed and
 * src/abis.ts (and the committed abis/*.json, regenerated by CI) must be updated.
 *
 * ABI-01: the gate used to cover only 4 of the 7 contracts in contracts/src/.
 * ActionLogger (the INV-3 audit-event emitter), SpendPolicy (the INV-1 tumbling
 * window cap logic) and MerkleWhitelist were entirely outside it, so editing an
 * ActionLogger event field or a SpendPolicy error was undetectable. The target
 * list is now cross-checked against a directory scan of contracts/src/*.sol in
 * BOTH directions, so the list cannot silently fall behind the contracts again.
 *
 * ABI-02 (partial): the "no undeclared error" check used to union all four ABIs,
 * so a new error could never be attributed to the contract that introduced it.
 * It is now evaluated per contract, with the contract named in the failure.
 */
import { describe, expect, it } from "vitest";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join, dirname, basename, extname } from "node:path";
import { fileURLToPath } from "node:url";
import { ACTION_LOGGER_ABI, SIGILKIT_ERRORS_ABI } from "../src/abis.js";

const HERE = dirname(fileURLToPath(import.meta.url));

/**
 * Single source of truth for the ABI drift gate: the CI regeneration loop in
 * .github/workflows/ci.yml reads this same file, so a contract cannot be listed on one
 * side of the gate and omitted on the other.
 *
 * Regression this pins (BUG-2): SigilKitDelegator.json was committed and consumed here,
 * but was absent from the CI loop — so its ABI could go stale and still pass CI.
 */
function findRepoRoot(from: string): string {
  let dir = from;
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(dir, "scripts", "abi-targets.txt"))) return dir;
    dir = dirname(dir);
  }
  throw new Error("could not locate scripts/abi-targets.txt from " + from);
}

const REPO_ROOT = findRepoRoot(HERE);
const CONTRACTS_SRC = join(REPO_ROOT, "contracts", "src");
const ABIS_DIR = join(HERE, "..", "abis");

const GENERATOR_ABI_NAMES = readFileSync(join(REPO_ROOT, "scripts", "abi-targets.txt"), "utf8")
  .split("\n")
  .map((l) => l.replace(/#.*$/, "").trim())
  .filter((l) => l.length > 0);

const SOL_FILES = readdirSync(CONTRACTS_SRC).filter((f) => extname(f) === ".sol");

/**
 * The contract name CI passes to `forge inspect contracts/src/<name>.sol:<name>`, i.e.
 * the file stem. Pinned to equal the .sol filename by the "declares a top-level
 * contract of the same name" assertion below, because the CI loop builds both halves
 * of that address from one string.
 */
const CONTRACT_FILE_NAMES = SOL_FILES.map((f) => basename(f, ".sol"));

/**
 * Top-level Solidity definitions in one source file. Column-0 matches only, so
 * contracts declared inside another contract (or inside a function body) are ignored —
 * what the CI loop addresses is the file's own unit.
 */
function readTopLevelDefinitions(file: string): string[] {
  const source = readFileSync(join(CONTRACTS_SRC, file), "utf8");
  const names: string[] = [];
  for (const line of source.split("\n")) {
    const m = /^(?:abstract\s+contract|contract|library|interface)\s+([A-Za-z_$][\w$]*)/.exec(
      line,
    );
    if (m) names.push(m[1]!);
  }
  return names;
}

/** Set-difference of the two sides of the ABI-01 gate. Pure, so it is unit-testable. */
function diffTargetLists(
  contractFiles: string[],
  targets: string[],
): { missingFromTargets: string[]; danglingInTargets: string[] } {
  const listed = new Set(targets);
  const present = new Set(contractFiles);
  return {
    missingFromTargets: contractFiles.filter((n) => !listed.has(n)).sort(),
    danglingInTargets: targets.filter((n) => !present.has(n)).sort(),
  };
}

const TARGET_GAPS = diffTargetLists(CONTRACT_FILE_NAMES, GENERATOR_ABI_NAMES);

// Every listed contract must actually have a committed ABI — otherwise the gate is
// silently vacuous for that contract. Reported as an explicit failure (with the
// generation command) rather than an ENOENT crash, because the JSONs can only be
// produced by forge.
const MISSING_ABI_FILES = GENERATOR_ABI_NAMES.filter(
  (name) => !existsSync(join(ABIS_DIR, `${name}.json`)),
);

type AbiItem = {
  type: string;
  name?: string;
  stateMutability?: string;
  inputs?: Array<{ name: string; type: string; indexed?: boolean }>;
};

/**
 * Parsed ABI per contract, keyed by name. Contracts whose JSON is absent are omitted
 * here; MISSING_ABI_FILES is what reports them, so this loader never throws and the
 * per-contract error checks below still run for everything that IS generated.
 */
function loadGeneratedByContract(): Map<string, AbiItem[]> {
  const byContract = new Map<string, AbiItem[]>();
  for (const name of GENERATOR_ABI_NAMES) {
    const path = join(ABIS_DIR, `${name}.json`);
    if (!existsSync(path)) continue;
    byContract.set(name, JSON.parse(readFileSync(path, "utf8")) as AbiItem[]);
  }
  return byContract;
}

function loadGenerated(): AbiItem[] {
  const items: AbiItem[] = [];
  for (const abi of loadGeneratedByContract().values()) items.push(...abi);
  return items;
}

function signatureOf(item: AbiItem): string {
  const types = (item.inputs ?? []).map((i) => i.type).join(",");
  return `${item.name}(${types})`;
}

/**
 * The non-signature qualifiers that change wire behaviour, per item kind:
 *  - functions: `stateMutability`, so a `view` -> `nonpayable` flip cannot hide behind an
 *    unchanged `name(inputs)` signature. Compared only when the hand-declared fragment
 *    carries one — src/abis.ts declares event/error fragments, which have no
 *    stateMutability — so this is the backward-compatible progressive form.
 *  - events: the per-input `indexed` flags that decodeEventLog depends on. Those are
 *    always declared, so they are compared strictly.
 */
function qualifiersOf(item: AbiItem): string {
  const inputs = item.inputs ?? [];
  if (item.type === "function") return item.stateMutability ?? "";
  if (item.type === "event") {
    return inputs.map((i) => (i.indexed ? "indexed" : "nonindexed")).join(",");
  }
  return "";
}

/**
 * Compares one hand-declared fragment against its generated match, returning
 * human-readable drift descriptions (empty when the fragment is faithful). Pure, so
 * the matching rules themselves are unit-testable below.
 */
function compareFragment(declared: AbiItem, match: AbiItem | undefined): string[] {
  if (!match) return [`${signatureOf(declared)} missing from generated ABIs`];
  const problems: string[] = [];
  const declaredInputs = declared.inputs ?? [];
  const matchInputs = match.inputs ?? [];
  for (let i = 0; i < declaredInputs.length; i++) {
    // Indexed flags must match for events (decodeEventLog depends on them).
    if (declaredInputs[i]!.indexed !== matchInputs[i]?.indexed) {
      problems.push(`${signatureOf(declared)} input ${i} indexed flag`);
    }
  }
  // Progressive: only compare stateMutability when the declaration actually has one.
  if (declared.type === "function") {
    const want = qualifiersOf(declared);
    if (want !== "" && qualifiersOf(match) !== want) {
      problems.push(
        `${signatureOf(declared)} stateMutability "${qualifiersOf(match)}" != "${want}"`,
      );
    }
  }
  return problems;
}

/**
 * Error/event declarations read straight out of the .sol sources.
 *
 * **Why this exists (the false-green this closes).** Every other check in this file
 * compares `src/abis.ts` against the **committed** `abis/*.json`. Those JSONs are produced
 * by `forge inspect` in CI and then committed, so the gate only ever proves that the
 * hand-written fragments match the *last generated* snapshot. Change
 * `ActionLogger.ActionLogged`'s `uint48` to `uint64` in Solidity, forget to regenerate,
 * commit both edits — and the gate compares the stale JSON against `src/abis.ts`, finds
 * them identical, and passes. The one failure mode the gate exists to prevent (contract
 * changed, ABI not regenerated) is the one it structurally cannot see. Nothing in the test
 * suite called forge, so locally it was always green.
 *
 * Reading the declarations from `contracts/src/*.sol` closes that: the .sol is the input
 * nobody can forget to edit. It is a *text* comparison, not a compiler, so it deliberately
 * does not attempt to understand Solidity — only the flat `event`/`error` forms this
 * codebase actually uses, with inherited members resolved via Solidity's C3-linearized
 * `is`/`contract` graph. Anything it cannot parse is reported rather than skipped, so the
 * parser degrading is a failure and not another silent pass.
 */
type SolDeclaration = {
  kind: "event" | "error";
  name: string;
  /** Canonical `name(type,type)` — the same shape `signatureOf` produces for the ABI. */
  signature: string;
  /** Per-parameter `indexed` flags, for events only. */
  indexed: (boolean | undefined)[];
  /** The contract that literally contains the declaration. */
  declaredIn: string;
  /** The contract the ABI is generated for (the inheriting one). */
  owner: string;
};

/**
 * Canonicalises a Solidity type expression to the spelling `forge inspect` emits, so the
 * two sides of the comparison are comparable as plain strings.
 *
 * Three normalisations matter, and each one is a case where a naive read of the
 * declaration would report drift that does not exist:
 *  - bare `uint`/`int` widen to `uint256`/`int256` (the compiler does this silently);
 *  - a nested tuple keeps its parentheses and canonicalises its own members;
 *  - an array suffix is preserved verbatim (`address[]` vs `address[3]` are different
 *    types, so the dimension must not be dropped).
 */
function canonicalSolType(raw: string): string {
  // Strip the parameter NAME and data-location keywords while whitespace still exists.
  // This must happen BEFORE whitespace is collapsed: `\s+name$` can no longer match once
  // `uint a` has become `uinta`, which silently produced `uinta`/`addressb` for tuple members.
  const bare = raw
    .trim()
    .replace(/\b(indexed|memory|storage|calldata|constant|immutable|payable)\b/g, " ")
    .replace(/\s+[A-Za-z_$][\w$]*$/, "");
  const t = bare.replace(/\s+/g, "");
  if (t === "") return "";
  // Recurse into tuple members: `(uint a, address b)[]` -> `(uint256,address)[]`.
  //
  // Match against `bare`, NOT the whitespace-collapsed `t`: splitting the collapsed form would
  // hand `uinta` / `addressb` to the recursion, and the name-stripping above can no longer
  // fire because the separating space is already gone. Splitting the preserved text keeps
  // `uint a` intact long enough for each member to canonicalise itself.
  const tuple = /^\(([\s\S]*)\)(\[\d*\])*$/.exec(bare);
  if (tuple) {
    const inner = splitParams(tuple[1]!)
      .map((p) => canonicalSolType(p))
      .filter((x) => x !== "");
    const suffix = /(\[\d*\])*$/.exec(t)![1] ?? "";
    return `(${inner.join(",")})${suffix}`;
  }
  const arr = /^([A-Za-z_$][\w$]*)((?:\[\d*\])*)$/.exec(t);
  if (!arr) return t;
  const base = arr[1]!;
  const suffix = arr[2] ?? "";
  if (/^u?int\d*$/.test(base)) {
    return `${base === "uint" ? "uint256" : base === "int" ? "int256" : base}${suffix}`;
  }
  if (/^bytes\d+$/.test(base) || base === "address" || base === "bool" || base === "string") {
    return `${base}${suffix}`;
  }
  // A user-defined struct/enum/contract name: keep it, including any array suffix.
  return `${base}${suffix}`;
}

/** Splits a parameter list on top-level commas, respecting nested tuples and arrays. */
function splitParams(src: string): string[] {
  const out: string[] = [];
  let depth = 0;
  let current = "";
  for (const ch of src) {
    if (ch === "(" || ch === "[") depth++;
    else if (ch === ")" || ch === "]") depth--;
    if (ch === "," && depth === 0) {
      out.push(current);
      current = "";
      continue;
    }
    current += ch;
  }
  if (current.trim() !== "") out.push(current);
  return out.map((p) => p.trim()).filter((p) => p.length > 0);
}

/**
 * Parses `event`/`error` declarations out of one Solidity source.
 *
 * Handles the two declaration shapes in this repo: single-line
 * (`error PerActionCapExceeded(uint256 value, uint256 cap);`) and multi-line
 * (`event ActionLogged(\n  bytes32 indexed agentId,\n  ...\n); event X;`). Scans by
 * brace/paren depth rather than by line, so a declaration spanning lines — or several on
 * one line — is captured whole.
 */
function parseDeclarations(rawSource: string, contract: string): {
  decls: Omit<SolDeclaration, "owner">[];
  /** Contracts named in `is X, Y` / `contract X is Y` clauses, i.e. the base graph. */
  bases: string[];
} {
  // Blank out comments across the WHOLE file before scanning. This has to happen here
  // rather than on each parameter list: a commented-out `// error Foo(uint256 x);` is
  // itself a declaration-shaped match, so the scanner would pick it up before any
  // parameter-level stripping could apply. Replaced with spaces (not deleted) so the
  // byte offsets the brace-walk relies on stay valid.
  const source = rawSource
    .replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, " "))
    .replace(/\/\/[^\n]*/g, (m) => " ".repeat(m.length));

  const decls: Omit<SolDeclaration, "owner">[] = [];

  // Base contracts, for resolving inherited members.
  const bases: string[] = [];
  const inheritRe = /(?:^|\n)\s*(?:abstract\s+)?(?:contract|interface|library)\s+\w+\s+is\s+([^{]+)\{/g;
  for (let m = inheritRe.exec(source); m; m = inheritRe.exec(source)) {
    for (const part of m[1]!.split(",")) {
      const name = part.trim().split(/[\s(]/)[0];
      if (name) bases.push(name);
    }
  }

  const declRe = /\b(event|error)\s+([A-Za-z_$][\w$]*)\s*\(/g;
  for (let m = declRe.exec(source); m; m = declRe.exec(source)) {
    const kind = m[1] as "event" | "error";
    const name = m[2]!;
    // Walk to the matching close paren.
    let depth = 1;
    let i = declRe.lastIndex;
    while (i < source.length && depth > 0) {
      const ch = source[i]!;
      if (ch === "(") depth++;
      else if (ch === ")") depth--;
      i++;
    }
    const inner = source.slice(declRe.lastIndex, i - 1);
    // Comments were already stripped from the whole source above, so `inner` cannot
    // contain a commented-out parameter that would read as a real one.
    const params = splitParams(inner);
    const types: string[] = [];
    const indexed: (boolean | undefined)[] = [];
    for (const p of params) {
      const isIndexed = kind === "event" && /\bindexed\b/.test(p);
      // The type is what remains once the qualifiers and the trailing parameter name are
      // removed. `bytes32 indexed agentId` -> `bytes32`; `uint256` -> `uint256`;
      // `(uint256 a, address b) inner` -> `(uint256 a, address b)`.
      const typeExpr = p
        .replace(/\b(indexed|memory|storage|calldata|constant|immutable|payable)\b/g, " ")
        .trim();
      const withoutName = typeExpr.replace(/\s+[A-Za-z_$][\w$]*$/, "");
      const canonical = canonicalSolType(withoutName || typeExpr);
      if (canonical === "") continue;
      types.push(canonical);
      indexed.push(isIndexed ? true : undefined);
    }
    decls.push({
      kind,
      name,
      signature: `${name}(${types.join(",")})`,
      indexed,
      declaredIn: contract,
    });
    declRe.lastIndex = i;
  }
  return { decls, bases };
}

/** Every .sol in contracts/src, keyed by contract name (= file stem, pinned above). */
const SOURCE_DECLARATIONS: SolDeclaration[] = (() => {
  const parsed = new Map<string, { decls: Omit<SolDeclaration, "owner">[]; bases: string[] }>();
  for (const name of CONTRACT_FILE_NAMES) {
    parsed.set(name, parseDeclarations(readFileSync(join(CONTRACTS_SRC, `${name}.sol`), "utf8"), name));
  }
  // Resolve inheritance: an owner sees its own declarations plus every base's, C3-ized.
  // Solidity requires the linearization order to be consistent; for conflict detection
  // the exact order does not matter, only *which* bases contribute a given signature.
  const all: SolDeclaration[] = [];
  const seen = new Set<string>();
  for (const owner of CONTRACT_FILE_NAMES) {
    const chain: string[] = [];
    const visit = (name: string): void => {
      if (chain.includes(name)) return; // already visited; also breaks inheritance cycles
      chain.push(name);
      for (const base of parsed.get(name)?.bases ?? []) visit(base);
    };
    visit(owner);
    for (const unit of chain) {
      for (const d of parsed.get(unit)?.decls ?? []) {
        const key = `${owner}:${d.kind}:${d.signature}`;
        if (seen.has(key)) continue;
        seen.add(key);
        all.push({ ...d, owner });
      }
    }
  }
  return all;
})();

/**
 * Errors in one contract's generated ABI that src/abis.ts does not declare. Deduplicated
 * by signature (one declaration per name, as SIGILKIT_ERRORS_ABI does) and returned
 * without an owner — the caller prefixes the contract name, so the report always says
 * which .sol introduced the error.
 */
function unattributedErrors(abi: AbiItem[], declaredSigs: Set<string>): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of abi) {
    if (item.type !== "error") continue;
    const sig = signatureOf(item);
    if (seen.has(sig)) continue;
    seen.add(sig);
    if (!declaredSigs.has(sig)) out.push(sig);
  }
  return out;
}

/**
 * Same-named events/errors that do not agree across the generated ABIs.
 *
 * Regression this pins (found by negative-testing ABI-01): SessionKeyManager,
 * SigilKitDelegator and ActionLog7579Executor all *inherit* ActionLogger, so its
 * events appear in several ABIs. A union lookup therefore finds the fragment in a
 * sibling's still-stale copy, and changing an ActionLogger event field (uint48 ->
 * uint64) passed the gate as long as the inheritors had not been recompiled. Inherited
 * declarations must agree everywhere they appear, otherwise decodeEventLog filters
 * built from one ABI silently miss events emitted under another.
 */
function divergentDeclarations(byContract: Map<string, AbiItem[]>): string[] {
  // key: "<type> <name>" -> signature -> contracts declaring it that way
  const seen = new Map<string, Map<string, Set<string>>>();
  for (const [contract, abi] of byContract) {
    for (const item of abi) {
      if (item.type !== "event" && item.type !== "error") continue;
      const key = `${item.type} ${item.name}`;
      const bySig = seen.get(key) ?? new Map<string, Set<string>>();
      const owners = bySig.get(signatureOf(item)) ?? new Set<string>();
      owners.add(contract);
      bySig.set(signatureOf(item), owners);
      seen.set(key, bySig);
    }
  }
  const out: string[] = [];
  for (const [key, bySig] of [...seen.entries()].sort()) {
    if (bySig.size < 2) continue;
    out.push(
      `${key} declared inconsistently: ` +
        [...bySig.entries()]
          .map(([sig, owners]) => `${sig} in [${[...owners].sort().join(", ")}]`)
          .join(" vs "),
    );
  }
  return out;
}

const GENERATED_BY_CONTRACT = loadGeneratedByContract();

/** The three contracts that were outside the gate entirely (ABI-01). */
const NEWLY_GATED = ["ActionLogger", "SpendPolicy", "MerkleWhitelist"] as const;

describe("ABI drift gate (E5)", () => {
  const generated = loadGenerated();

  it("abis/*.json exist and contain every hand-declared event/error fragment", () => {
    expect(generated.length).toBeGreaterThan(10);
    const generatedSigs = new Map(generated.map((i) => [signatureOf(i), i]));
    const problems = [...ACTION_LOGGER_ABI, ...SIGILKIT_ERRORS_ABI].flatMap((fragment) => {
      const item = fragment as unknown as AbiItem;
      return compareFragment(item, generatedSigs.get(signatureOf(item)));
    });
    expect(
      problems,
      "src/abis.ts drifted from the generated ABIs — update src/abis.ts and the committed abis/*.json",
    ).toEqual([]);
  });

  it("abi-targets.txt covers every contract in contracts/src (ABI-01, forward direction)", () => {
    // A new .sol file nobody added to the target list would be invisible to both the CI
    // regeneration loop and this gate. That is exactly how ActionLogger, SpendPolicy and
    // MerkleWhitelist escaped the gate in the first place.
    expect(
      TARGET_GAPS.missingFromTargets,
      "add these contracts to scripts/abi-targets.txt (and commit their abis/<name>.json) — " +
        "a contract outside the list is outside the ABI drift gate",
    ).toEqual([]);
  });

  it("every abi-targets.txt entry has a matching contracts/src file (ABI-01, reverse)", () => {
    // A renamed or deleted .sol leaves the target list dangling: CI would fail inside
    // `forge inspect`, and a stale abis/<name>.json would keep being diffed forever.
    expect(
      TARGET_GAPS.danglingInTargets,
      "these names in scripts/abi-targets.txt have no contracts/src/<name>.sol — " +
        "remove them from the list and delete the orphaned abis/<name>.json",
    ).toEqual([]);
  });

  it("each contracts/src file declares a top-level contract of the same name", () => {
    // The CI loop addresses contracts as contracts/src/<name>.sol:<name>, so the
    // filename and the Solidity name must agree or forge inspect cannot resolve it.
    const mismatches: string[] = [];
    const ambiguous: string[] = [];
    for (const file of SOL_FILES) {
      const defs = readTopLevelDefinitions(file);
      const stem = basename(file, ".sol");
      if (defs.length === 0) {
        mismatches.push(`${file} declares no top-level contract/library`);
      } else if (!defs.includes(stem)) {
        mismatches.push(`${file} declares [${defs.join(", ")}], expected a top-level "${stem}"`);
      }
      if (defs.length > 1) {
        // Two units in one file: forge inspect <file>:<name> covers only one of them.
        ambiguous.push(`${file} declares [${defs.join(", ")}] — list each name separately`);
      }
    }
    expect(mismatches, "contracts/src file/contract name mismatch").toEqual([]);
    expect(ambiguous, "a file with multiple top-level contracts is only half-covered").toEqual(
      [],
    );
  });

  it("the target list is directory-derived, not hand-pinned (full depth)", () => {
    // Equality with the directory scan replaces the old hand-pinned floor; >= 7 still
    // pins the absolute count so mass-deleting contracts/src/*.sol cannot make a
    // shrinking gate look green.
    expect(GENERATOR_ABI_NAMES.length).toBe(CONTRACT_FILE_NAMES.length);
    expect(GENERATOR_ABI_NAMES.length).toBeGreaterThanOrEqual(7);
  });

  it("ActionLogger, SpendPolicy and MerkleWhitelist are inside the gate (ABI-01 pin)", () => {
    // These three carried INV-3's audit event, INV-1's cap errors and the whitelist
    // verifier respectively, and were absent from both sides of the drift gate.
    for (const name of NEWLY_GATED) {
      expect(GENERATOR_ABI_NAMES, `${name}.sol is outside the ABI drift gate`).toContain(name);
      expect(CONTRACT_FILE_NAMES).toContain(name);
    }
  });

  it("no contract declares an ERROR that src/abis.ts lacks, checked per contract", () => {
    // Errors must be complete — decodeSigilKitError's registry covers the full custom
    // error surface. Events are decoded per-need (ActionLogger events live in
    // ACTION_LOGGER_ABI); admin lifecycle events are intentionally not mirrored.
    // Per-contract (not unioned) so a new error is attributed to the contract that
    // introduced it, rather than reported without an owner.
    const declaredSigs = new Set(
      [...ACTION_LOGGER_ABI, ...SIGILKIT_ERRORS_ABI].map((i) =>
        signatureOf(i as unknown as AbiItem),
      ),
    );
    const unattributed = [...GENERATED_BY_CONTRACT.entries()].flatMap(([contract, abi]) =>
      unattributedErrors(abi, declaredSigs).map((sig) => `${contract}: ${sig}`),
    );
    expect(
      unattributed,
      "new contract errors must be added to src/abis.ts (and decoded where relevant); " +
        "each entry is prefixed with the contract that introduced it",
    ).toEqual([]);
  });

  it("inherited events and errors agree across every contract that declares them", () => {
    // The union lookup above matches a fragment against whichever ABI happens to
    // contain it, so a contract inheriting a changed declaration can mask the drift.
    // This pins that all copies of a same-named event/error are identical.
    expect(
      divergentDeclarations(GENERATED_BY_CONTRACT),
      "regenerate the ABIs of every inheriting contract too (see scripts/abi-targets.txt) — " +
        "a shared event/error must not differ between contracts",
    ).toEqual([]);
  });

  it("every contract in scripts/abi-targets.txt has a committed ABI file", () => {
    // ABI-01: ActionLogger/SpendPolicy/MerkleWhitelist entered the list while forge was
    // unavailable locally, so their JSONs could not be generated here. This fails
    // explicitly (rather than vacuously passing or crashing with ENOENT) and prints the
    // exact command; CI's regeneration loop produces them on the first run with forge.
    expect(
      MISSING_ABI_FILES,
      "generate the missing ABI JSONs from the repo root with Foundry on PATH:\n" +
        '  while IFS= read -r c; do\n' +
        "    c=\"${c%%#*}\"; c=\"$(echo \"$c\" | tr -d '[:space:]')\"\n" +
        '    [ -z "$c" ] && continue\n' +
        '    forge inspect "contracts/src/$c.sol:$c" abi --json > "packages/core/abis/$c.json"\n' +
        "  done < scripts/abi-targets.txt\n" +
        "or remove the contract from scripts/abi-targets.txt. Never hand-write these files.",
    ).toEqual([]);
  });

  it("every committed abis/*.json is nonempty, parseable JSON (SK-22)", () => {
    // A zero-byte or malformed stray JSON in abis/ is invalid for any glob consumer
    // (regression: an empty SessionKeyManager...SigilKitDelegator.json was committed).
    // This covers files OUTSIDE abi-targets.txt too, so strays cannot hide.
    const files = readdirSync(ABIS_DIR).filter((f) => f.endsWith(".json"));
    expect(files.length).toBeGreaterThanOrEqual(GENERATOR_ABI_NAMES.length);
    for (const file of files) {
      const raw = readFileSync(join(ABIS_DIR, file), "utf8");
      expect(raw.trim().length, `${file} is empty`).toBeGreaterThan(0);
      let parsed: unknown;
      try {
        parsed = JSON.parse(raw);
      } catch (error) {
        throw new Error(`${file} is not valid JSON: ${error}`);
      }
      expect(Array.isArray(parsed), `${file} must be an ABI array`).toBe(true);
    }
  });

  it("the ABI target list covers the EIP-7702 delegator (BUG-2 regression pin)", () => {
    // SigilKitDelegator.json was committed and consumed by this gate, but was absent
    // from the CI regeneration loop — so a change to SigilKitDelegator.sol could land
    // with a stale committed ABI and still pass CI. Pin it into the shared list.
    expect(GENERATOR_ABI_NAMES).toContain("SigilKitDelegator");
  });

  it("CI regenerates ABIs from the same shared list (both sides of the gate agree)", () => {
    // The gate is only meaningful if CI and this test read the SAME source of truth.
    const ci = readFileSync(join(REPO_ROOT, ".github", "workflows", "ci.yml"), "utf8");
    expect(
      ci,
      "ci.yml must regenerate ABIs from scripts/abi-targets.txt, not a hand-written list",
    ).toContain("scripts/abi-targets.txt");
    // Guard against a re-introduced hardcoded loop.
    expect(ci).not.toMatch(/for c in SessionKeyManager/);
  });
});

/**
 * Source-of-truth gate: the .sol files, compared without forge.
 *
 * These assertions exist because every check in the block above is downstream of the
 * committed `abis/*.json`, and therefore cannot observe a contract edit that was not
 * regenerated. See the {@link SOURCE_DECLARATIONS} comment for the full failure mode.
 */
describe("ABI drift gate: contracts/src is the source of truth (no forge required)", () => {
  const declaredSigs = new Set(
    [...ACTION_LOGGER_ABI, ...SIGILKIT_ERRORS_ABI].map((i) => signatureOf(i as unknown as AbiItem)),
  );

  it("the source parser actually found declarations (a silently empty parse is a false green)", () => {
    // If the parser ever stops matching the Solidity in this repo, every assertion below
    // would pass vacuously. This pins that it is reading real data, and that it is
    // reading a plausible amount of it.
    const sourceErrors = SOURCE_DECLARATIONS.filter((d) => d.kind === "error");
    const sourceEvents = SOURCE_DECLARATIONS.filter((d) => d.kind === "event");
    expect(sourceErrors.length, "no errors parsed from contracts/src — parser regression").toBeGreaterThan(20);
    expect(sourceEvents.length, "no events parsed from contracts/src — parser regression").toBeGreaterThan(5);
    // PerActionCapExceeded is the canonical INV-1 cap error; if the parser can find that
    // one it is reading the real files rather than matching something incidental.
    expect(sourceErrors.map((d) => d.signature)).toContain(
      "PerActionCapExceeded(uint256,uint256)",
    );
  });

  it("every error declared in the .sol sources is mirrored in src/abis.ts", () => {
    const missing = [...new Set(
      SOURCE_DECLARATIONS.filter((d) => d.kind === "error" && !declaredSigs.has(d.signature))
        .map((d) => `${d.declaredIn}: ${d.signature}`),
    )].sort();
    expect(
      missing,
      "these errors exist in contracts/src but not in src/abis.ts, so decodeSigilKitError " +
        "cannot name them; add them to SIGILKIT_ERRORS_ABI",
    ).toEqual([]);
  });

  it("every error in the committed ABIs still exists in the .sol sources (stale-ABI direction)", () => {
    // The other direction: an ABI entry whose Solidity declaration is gone means the JSON
    // is stale, which is exactly the "regenerate the ABIs" case — reported here so it is
    // caught locally rather than only by CI's `git diff --exit-code`.
    const sourceSigs = new Set(SOURCE_DECLARATIONS.map((d) => d.signature));
    const stale = [...GENERATED_BY_CONTRACT.entries()].flatMap(([contract, abi]) =>
      abi
        .filter((item) => item.type === "error" && !sourceSigs.has(signatureOf(item)))
        .map((item) => `${contract}: ${signatureOf(item)}`),
    );
    expect(
      [...new Set(stale)].sort(),
      "these errors are in the committed abis/*.json but no longer in the .sol sources — " +
        "regenerate with scripts/abi-targets.txt (forge inspect ... > packages/core/abis/<name>.json)",
    ).toEqual([]);
  });

  it("ActionLogged's shape in the .sol matches the hand-declared fragment byte-for-byte", () => {
    // The INV-3 audit event, pinned directly against the source. This is the assertion
    // that would have caught a uint48 -> uint64 edit in ActionLogger.sol.
    const fromSource = SOURCE_DECLARATIONS.find(
      (d) => d.kind === "event" && d.name === "ActionLogged",
    );
    expect(fromSource, "ActionLogged not found in contracts/src — parser regression").toBeTruthy();
    const declared = ACTION_LOGGER_ABI.find(
      (i) => (i as unknown as AbiItem).name === "ActionLogged",
    ) as unknown as AbiItem;
    // `fromSource` is a SolDeclaration, which carries a precomputed `signature`; it has no
    // `inputs` array. Passing it to `signatureOf` (typed for AbiItem) silently read
    // `.inputs === undefined` and produced `ActionLogged()`, so the left-hand side was a
    // constant and this assertion could never have caught the uint48 -> uint64 edit it guards.
    expect(fromSource!.signature).toBe(signatureOf(declared));
    expect(fromSource!.indexed).toEqual((declared.inputs ?? []).map((i) => (i.indexed ? true : undefined)));
  });

  it("no hand-declared event/error fragment lacks a .sol declaration", () => {
    // Catches the mirror image: a fragment invented in src/abis.ts for a declaration that
    // does not exist, which decodeEventLog would then silently never match.
    const sourceSigs = new Set(SOURCE_DECLARATIONS.map((d) => d.signature));
    const invented = [...ACTION_LOGGER_ABI, ...SIGILKIT_ERRORS_ABI]
      .map((i) => i as unknown as AbiItem)
      .filter((i) => i.type === "event" || i.type === "error")
      .filter((i) => !sourceSigs.has(signatureOf(i)))
      .map((i) => signatureOf(i));
    expect(
      [...new Set(invented)].sort(),
      "src/abis.ts declares fragments with no matching event/error in contracts/src",
    ).toEqual([]);
  });
});

/**
 * Self-tests for the rules the gate above relies on. These pin the *behaviour* of the
 * directory scan and the signature comparison against synthetic fixtures, so a future
 * refactor that weakens either rule fails here instead of silently narrowing coverage.
 * No real files are mutated.
 */
describe("ABI gate rules (self-tests)", () => {
  it("adding a contracts/src file without a target-list entry is detected", () => {
    const diff = diffTargetLists([...CONTRACT_FILE_NAMES, "NewContract"], GENERATOR_ABI_NAMES);
    expect(diff.missingFromTargets).toEqual(["NewContract"]);
  });

  it("removing a target-list entry without deleting the .sol file is detected", () => {
    const withoutSpendPolicy = GENERATOR_ABI_NAMES.filter((n) => n !== "SpendPolicy");
    const diff = diffTargetLists(CONTRACT_FILE_NAMES, withoutSpendPolicy);
    expect(diff.missingFromTargets).toEqual(["SpendPolicy"]);
  });

  it("a renamed contract leaves a dangling target-list entry", () => {
    // The exact ABI-01 failure mode: SpendPolicy.sol -> SpendPolicyV2.sol, list untouched.
    const diff = diffTargetLists(
      CONTRACT_FILE_NAMES.filter((n) => n !== "SpendPolicy").concat("SpendPolicyV2"),
      GENERATOR_ABI_NAMES,
    );
    expect(diff.danglingInTargets).toEqual(["SpendPolicy"]);
  });

  it("the real contracts and the real target list agree in both directions", () => {
    expect(TARGET_GAPS).toEqual({ missingFromTargets: [], danglingInTargets: [] });
  });

  it("a view -> nonpayable change is caught by the signature comparison", () => {
    // Same name(inputs): only stateMutability differs, which signatureOf alone cannot see.
    const declared = {
      type: "function",
      name: "balanceOf",
      stateMutability: "view",
      inputs: [{ name: "account", type: "address" }],
    } as AbiItem;
    const asNonpayable = {
      type: "function",
      name: "balanceOf",
      stateMutability: "nonpayable",
      inputs: [{ name: "account", type: "address" }],
    } as AbiItem;
    expect(signatureOf(declared)).toBe(signatureOf(asNonpayable));
    expect(compareFragment(declared, asNonpayable)).toEqual([
      'balanceOf(address) stateMutability "nonpayable" != "view"',
    ]);
    expect(compareFragment(declared, { ...asNonpayable, stateMutability: "view" })).toEqual([]);
  });

  it("a declaration without stateMutability is not compared (backward compatible)", () => {
    // src/abis.ts declares event/error fragments, which have no stateMutability, so
    // nothing new is enforced against the committed abis/*.json.
    const declared = { type: "error", name: "KeyUnknown", inputs: [] } as AbiItem;
    const match = { type: "error", name: "KeyUnknown", inputs: [] } as AbiItem;
    expect(compareFragment(declared, match)).toEqual([]);
    expect(compareFragment(declared, undefined)).toEqual([
      "KeyUnknown() missing from generated ABIs",
    ]);
  });

  it("an indexed flag flip is still caught for events", () => {
    const declared = {
      type: "event",
      name: "ActionLogged",
      inputs: [
        { name: "agentId", type: "bytes32", indexed: true },
        { name: "value", type: "uint256", indexed: false },
      ],
    } as AbiItem;
    const unindexed = {
      type: "event",
      name: "ActionLogged",
      inputs: [
        { name: "agentId", type: "bytes32", indexed: false },
        { name: "value", type: "uint256", indexed: false },
      ],
    } as AbiItem;
    expect(compareFragment(declared, unindexed)).toEqual([
      "ActionLogged(bytes32,uint256) input 0 indexed flag",
    ]);
  });

  it("an undeclared error is attributed to its owning contract", () => {
    const declared = new Set(["KeyUnknown()"]);
    const abi = [
      { type: "error", name: "KeyUnknown", inputs: [] },
      {
        type: "error",
        name: "PerActionCapExceeded",
        inputs: [
          { name: "value", type: "uint256" },
          { name: "cap", type: "uint256" },
        ],
      },
    ] as AbiItem[];
    // Per-contract mapping is what supplies the owner the old unioned check lost.
    const attributed = [...new Map([["SpendPolicy", abi]]).entries()].flatMap(
      ([contract, items]) => unattributedErrors(items, declared).map((sig) => `${contract}: ${sig}`),
    );
    expect(attributed).toEqual(["SpendPolicy: PerActionCapExceeded(uint256,uint256)"]);
  });

  it("a declared error produces no attribution report", () => {
    const declared = new Set(["PerActionCapExceeded(uint256,uint256)"]);
    const abi = [
      {
        type: "error",
        name: "PerActionCapExceeded",
        inputs: [
          { name: "value", type: "uint256" },
          { name: "cap", type: "uint256" },
        ],
      },
    ] as AbiItem[];
    expect(unattributedErrors(abi, declared)).toEqual([]);
  });
});

/**
 * Self-tests for the source parser. Without these, a parser that silently stopped matching
 * the Solidity in this repo would turn every source-of-truth assertion above into a
 * vacuous pass — which is the same false-green class this whole block exists to remove.
 */
describe("source declaration parser (self-tests)", () => {
  it("parses a single-line error", () => {
    const { decls } = parseDeclarations(
      "error PerActionCapExceeded(uint256 value, uint256 cap);",
      "SpendPolicy",
    );
    expect(decls).toHaveLength(1);
    expect(decls[0]!.signature).toBe("PerActionCapExceeded(uint256,uint256)");
    expect(decls[0]!.kind).toBe("error");
  });

  it("parses a multi-line event with indexed flags", () => {
    const { decls } = parseDeclarations(
      `event ActionLogged(
         bytes32 indexed agentId,
         address indexed target,
         bytes4 indexed selector,
         uint256 value,
         bytes32 rationaleHash,
         uint48 timestamp
       );`,
      "ActionLogger",
    );
    expect(decls).toHaveLength(1);
    expect(decls[0]!.signature).toBe(
      "ActionLogged(bytes32,address,bytes4,uint256,bytes32,uint48)",
    );
    // The first three parameters are indexed; the rest are not. The flags decide which
    // parameters land in topics, so getting them wrong would break decodeEventLog.
    expect(decls[0]!.indexed).toEqual([true, true, true, undefined, undefined, undefined]);
  });

  it("parses two declarations on one line", () => {
    const { decls } = parseDeclarations("error A(); error B(uint256 x);", "X");
    expect(decls.map((d) => d.signature)).toEqual(["A()", "B(uint256)"]);
  });

  it("parses array parameter types, keeping each array suffix", () => {
    const { decls } = parseDeclarations(
      "error E(address[] targets, uint256[] amounts);",
      "X",
    );
    expect(decls[0]!.signature).toBe("E(address[],uint256[])");
  });

  it("ignores a commented-out declaration", () => {
    const { decls } = parseDeclarations(
      `// error CommentedOut(uint256 x);
       /* error BlockCommented(uint256 y); */
       error Real(uint256 z);`,
      "X",
    );
    expect(decls.map((d) => d.signature)).toEqual(["Real(uint256)"]);
  });

  it("reads the inheritance clause so inherited members are attributed to the inheritor", () => {
    const { bases } = parseDeclarations(
      "abstract contract Base { }\ncontract Child is Base, Other { }",
      "Child",
    );
    expect(bases).toEqual(["Base", "Other"]);
  });

  it("canonicalises bare uint/int to their 32-byte forms", () => {
    const { decls } = parseDeclarations("error E(uint a, int b, uint8 c);", "X");
    // Solidity widens bare `uint`/`int` to 256 bits, and so does forge — comparing the
    // raw token would report drift on every contract that uses the short form.
    expect(decls[0]!.signature).toBe("E(uint256,int256,uint8)");
  });

  it("keeps a nested tuple as ONE parameter and canonicalises its members", () => {
    const { decls } = parseDeclarations(
      "error E((uint a, address b) inner, bytes4 selector);",
      "X",
    );
    expect(decls).toHaveLength(1);
    // The tuple's inner comma must not split it into two parameters, and its members
    // must be canonicalised the same way a top-level type would be.
    expect(decls[0]!.signature).toBe("E((uint256,address),bytes4)");
  });

  it("preserves the dimension of a fixed-size array", () => {
    const { decls } = parseDeclarations("error E(bytes32[3] fixedArr);", "X");
    // `bytes32[3]` and `bytes32[]` are different ABI types; the dimension is load-bearing.
    expect(decls[0]!.signature).toBe("E(bytes32[3])");
  });
});
