/**
 * ABI drift gate (enhancement E5): every event/error fragment hand-declared in
 * src/abis.ts must exist, byte-for-byte (modulo internalType), in the compiler-
 * generated ABI JSONs under abis/. If this test fails, the contracts changed and
 * src/abis.ts (and the committed abis/*.json, regenerated by CI) must be updated.
 */
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { ACTION_LOGGER_ABI, SIGILKIT_ERRORS_ABI } from "../src/abis.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const GENERATOR_ABI_NAMES = [
  "SessionKeyManager",
  "SessionKey7579Module",
  "ActionLog7579Executor",
  "SigilKitDelegator",
] as const;

type AbiItem = {
  type: string;
  name?: string;
  inputs?: Array<{ name: string; type: string; indexed?: boolean }>;
};

function loadGenerated(): AbiItem[] {
  const items: AbiItem[] = [];
  for (const name of GENERATOR_ABI_NAMES) {
    const raw = JSON.parse(readFileSync(join(HERE, "..", "abis", `${name}.json`), "utf8")) as AbiItem[];
    items.push(...raw);
  }
  return items;
}

function signatureOf(item: AbiItem): string {
  const types = (item.inputs ?? []).map((i) => i.type).join(",");
  return `${item.name}(${types})`;
}

describe("ABI drift gate (E5)", () => {
  const generated = loadGenerated();

  it("abis/*.json exist and contain every hand-declared event/error fragment", () => {
    expect(generated.length).toBeGreaterThan(10);
    const generatedSigs = new Map(generated.map((i) => [signatureOf(i), i]));
    for (const fragment of [...ACTION_LOGGER_ABI, ...SIGILKIT_ERRORS_ABI]) {
      const item = fragment as unknown as AbiItem;
      const match = generatedSigs.get(signatureOf(item));
      expect(match, `${signatureOf(item)} missing from generated ABIs`).toBeDefined();
      // Indexed flags must match for events (decodeEventLog depends on them).
      const declaredInputs = item.inputs ?? [];
      const generatedInputs = match!.inputs ?? [];
      for (let i = 0; i < declaredInputs.length; i++) {
        expect(generatedInputs[i]?.indexed, `${signatureOf(item)} input ${i} indexed flag`).toBe(
          declaredInputs[i]!.indexed,
        );
      }
    }
  });

  it("generated ABIs declare no ERROR that abis.ts lacks (surfaces new items)", () => {
    // Errors must be complete — decodeSigilKitError's registry covers the full custom
    // error surface. Events are decoded per-need (ActionLogger events live in
    // ACTION_LOGGER_ABI); admin lifecycle events are intentionally not mirrored.
    const declared = new Set(
      [...ACTION_LOGGER_ABI, ...SIGILKIT_ERRORS_ABI].map((i) => signatureOf(i as unknown as AbiItem)),
    );
    const generatedErrors = generated
      .filter((i) => i.type === "error")
      .map((i) => signatureOf(i));
    const missing = generatedErrors.filter((sig) => !declared.has(sig));
    expect(
      missing,
      "new contract errors must be added to src/abis.ts (and decoded where relevant)",
    ).toEqual([]);
  });
});
